import AppKit
import Carbon
import Observation

enum ClipboardPolicy {
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "com.openray.generated",
    ]

    static func shouldCapture(types: Set<String>, sourceBundleID: String?, excluded: [String], secureInput: Bool)
        -> Bool
    {
        guard !secureInput, ignoredTypes.isDisjoint(with: types) else { return false }
        if let sourceBundleID,
            excluded.contains(where: { sourceBundleID == $0 || sourceBundleID.hasPrefix($0 + ".") })
        {
            return false
        }
        return true
    }
}

struct ClipboardCaptureContext: Sendable {
    var sourceName: String
    var sourceBundleID: String?
    var secureInput: Bool

    @MainActor static func current() -> ClipboardCaptureContext {
        let source = NSWorkspace.shared.frontmostApplication
        return ClipboardCaptureContext(
            sourceName: source?.localizedName ?? "Unknown app",
            sourceBundleID: source?.bundleIdentifier,
            secureInput: IsSecureEventInputEnabled())
    }
}

@MainActor
@Observable
final class ClipboardService {
    private(set) var accessMessage: String?
    private(set) var contentMessage: String?
    private(set) var isProcessing = false
    var usesGeneralPasteboard: Bool { pasteboard.name == .general }
    var changeCount: Int { pasteboard.changeCount }
    @ObservationIgnored private let store: LibraryStore
    @ObservationIgnored private let pasteboard: NSPasteboard
    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastChange: Int
    @ObservationIgnored private var lastPrune = Date.distantPast
    @ObservationIgnored private var captureGeneration = 0
    @ObservationIgnored private let imageProcessor: any ClipboardImagePreparing
    @ObservationIgnored private let captureContext: @MainActor () -> ClipboardCaptureContext
    @ObservationIgnored private var previousPolicy: CapturePolicy?

    private struct CapturePolicy: Equatable {
        var enabled: Bool
        var images: Bool
        var files: Bool
        var excluded: [String]
    }

    init(
        store: LibraryStore, pasteboard: NSPasteboard = .general,
        imageProcessor: any ClipboardImagePreparing = ClipboardImageProcessor.shared,
        captureContext: @escaping @MainActor () -> ClipboardCaptureContext = ClipboardCaptureContext.current
    ) {
        self.store = store
        self.pasteboard = pasteboard
        self.imageProcessor = imageProcessor
        self.captureContext = captureContext
        lastChange = pasteboard.changeCount
    }

    func configure() {
        timer?.invalidate()
        timer = nil
        lastChange = pasteboard.changeCount
        let preferences = store.database.preferences
        let policy = CapturePolicy(
            enabled: preferences.clipboardEnabled, images: preferences.capturesClipboardImages,
            files: preferences.capturesClipboardFiles, excluded: preferences.excludedClipboardBundleIDs)
        if previousPolicy != policy {
            captureGeneration += 1
            previousPolicy = policy
        }
        store.pruneClipboard()
        refreshAccessStatus()
        guard store.database.preferences.clipboardEnabled else { return }
        let timer = Timer(timeInterval: 0.75, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in await self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        captureGeneration += 1
    }

    func poll() async {
        guard store.database.preferences.clipboardEnabled, !isProcessing else { return }
        refreshAccessStatus()
        guard pasteboard.accessBehavior != .alwaysDeny else { return }
        if Date.now.timeIntervalSince(lastPrune) > 60 {
            store.pruneClipboard()
            lastPrune = .now
        }
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        let change = lastChange
        let generation = captureGeneration
        let copiedAt = Date.now
        let source = captureContext()
        guard
            ClipboardPolicy.shouldCapture(
                types: [], sourceBundleID: source.sourceBundleID,
                excluded: store.database.preferences.excludedClipboardBundleIDs,
                secureInput: source.secureInput)
        else { return }
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard
            ClipboardPolicy.shouldCapture(
                types: types, sourceBundleID: source.sourceBundleID,
                excluded: store.database.preferences.excludedClipboardBundleIDs,
                secureInput: source.secureInput)
        else { return }
        contentMessage = nil
        do {
            if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue) {
                guard store.database.preferences.capturesClipboardFiles else { return }
                let items = pasteboard.pasteboardItems ?? []
                guard items.count <= ClipboardLimits.fileCount else {
                    throw LibraryValidationError("A clipboard entry can contain up to 100 file references.")
                }
                var urls: [URL] = []
                for item in items {
                    guard let string = item.string(forType: .fileURL), let url = URL(string: string), url.isFileURL
                    else {
                        throw LibraryValidationError("The copied files could not be read as file references.")
                    }
                    if !urls.contains(url) { urls.append(url) }
                }
                let entry = ClipboardEntry(
                    content: .files(urls), copiedAt: copiedAt,
                    sourceName: source.sourceName, sourceBundleID: source.sourceBundleID)
                guard entry.isValid else {
                    throw LibraryValidationError("These file references exceed the supported clipboard limits.")
                }
                guard pasteboard.changeCount == change else { return }
                store.capture(entry)
            } else if types.contains(NSPasteboard.PasteboardType.png.rawValue)
                || types.contains(NSPasteboard.PasteboardType.tiff.rawValue)
            {
                guard store.database.preferences.capturesClipboardImages else { return }
                let type: NSPasteboard.PasteboardType =
                    types.contains(NSPasteboard.PasteboardType.png.rawValue) ? .png : .tiff
                guard let data = pasteboard.data(forType: type), pasteboard.changeCount == change else { return }
                isProcessing = true
                defer { isProcessing = false }
                let prepared = try await imageProcessor.prepare(data)
                guard !Task.isCancelled, generation == captureGeneration, store.database.preferences.clipboardEnabled,
                    store.database.preferences.capturesClipboardImages
                else { return }
                store.captureImage(
                    prepared, copiedAt: copiedAt, sourceName: source.sourceName, sourceBundleID: source.sourceBundleID)
            } else if let data = pasteboard.data(forType: .string) {
                guard data.count <= ClipboardLimits.textBytes else {
                    throw LibraryValidationError("This copied text exceeds the 128 KB clipboard-entry limit.")
                }
                guard let text = String(data: data, encoding: .utf8), pasteboard.changeCount == change else { return }
                store.capture(
                    ClipboardEntry(
                        text: text, copiedAt: copiedAt, sourceName: source.sourceName,
                        sourceBundleID: source.sourceBundleID))
            }
        } catch is CancellationError {
            return
        } catch {
            guard !Task.isCancelled, generation == captureGeneration else { return }
            contentMessage = error.localizedDescription
        }
    }

    func readText() -> String? { pasteboard.string(forType: .string) }

    func refreshAccessStatus() {
        guard store.database.preferences.clipboardEnabled else {
            accessMessage = nil
            return
        }
        switch pasteboard.accessBehavior {
        case .alwaysAllow: accessMessage = nil
        case .alwaysDeny:
            accessMessage =
                "macOS is blocking clipboard access. Allow OpenRay’s clipboard access in System Settings, then copy text again."
        case .default, .ask:
            accessMessage =
                "macOS may ask to allow clipboard access. For uninterrupted history, choose Always Allow for OpenRay’s clipboard access in System Settings."
        @unknown default:
            accessMessage = "Check OpenRay’s clipboard access in System Settings if copied text does not appear."
        }
    }

    @discardableResult
    func clearHistory() -> Bool {
        captureGeneration += 1
        lastChange = pasteboard.changeCount
        contentMessage = nil
        return store.update { $0.clipboard = [] }
    }

    @discardableResult
    func copy(_ text: String) -> Bool {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        return write([item])
    }

    @discardableResult
    func copy(_ entry: ClipboardEntry) -> Bool {
        contentMessage = nil
        guard entry.isValid else {
            contentMessage = "This saved clipboard entry is invalid."
            return false
        }
        switch entry.content {
        case .text(let text): return copy(text)
        case .image(let image):
            guard let data = store.imageData(for: image) else {
                contentMessage = "This saved image is missing or damaged. The current clipboard was not changed."
                return false
            }
            let item = NSPasteboardItem()
            item.setData(data, forType: .png)
            return write([item])
        case .files(let urls):
            let items = urls.map { url in
                let item = NSPasteboardItem()
                item.setString(url.absoluteString, forType: .fileURL)
                return item
            }
            return write(items)
        }
    }

    private func write(_ items: [NSPasteboardItem]) -> Bool {
        for item in items { item.setString("1", forType: NSPasteboard.PasteboardType("com.openray.generated")) }
        pasteboard.clearContents()
        let success = pasteboard.writeObjects(items)
        lastChange = pasteboard.changeCount
        return success
    }
}

@MainActor
enum SyntheticInput {
    static let marker: Int64 = 0x4F52_4159

    static func paste(into application: NSRunningApplication, expectedChangeCount: Int) async throws {
        guard AXIsProcessTrusted() else {
            throw LibraryValidationError(
                "Copied to the clipboard. Enable Accessibility in Settings for direct paste, or press ⌘V in your app.")
        }
        application.activate()
        for _ in 0..<20 {
            if NSWorkspace.shared.frontmostApplication?.processIdentifier == application.processIdentifier { break }
            try await Task.sleep(for: .milliseconds(25))
        }
        guard NSWorkspace.shared.frontmostApplication?.processIdentifier == application.processIdentifier,
            NSPasteboard.general.changeCount == expectedChangeCount,
            !IsSecureEventInputEnabled()
        else {
            throw LibraryValidationError("The target app or clipboard changed. Your text is copied; paste it with ⌘V.")
        }
        try key(CGKeyCode(kVK_ANSI_V), flags: .maskCommand)
    }

    static func replace(keyword: String, with text: String, in pid: pid_t) throws {
        guard AXIsProcessTrusted(), !IsSecureEventInputEnabled(),
            NSWorkspace.shared.frontmostApplication?.processIdentifier == pid
        else { return }
        // This path never touches the clipboard. Keywords are validated as ASCII.
        for _ in keyword { try key(CGKeyCode(kVK_Delete)) }
        for chunk in unicodeChunks(text) {
            guard let down = CGEvent(keyboardEventSource: nil, virtualKey: 0, keyDown: true),
                let up = CGEvent(keyboardEventSource: nil, virtualKey: 0, keyDown: false)
            else {
                throw LibraryValidationError("macOS could not insert the snippet.")
            }
            for event in [down, up] {
                event.keyboardSetUnicodeString(stringLength: chunk.count, unicodeString: chunk)
                event.setIntegerValueField(.eventSourceUserData, value: marker)
                event.post(tap: .cghidEventTap)
            }
        }
    }

    nonisolated static func unicodeChunks(_ text: String) -> [[UInt16]] {
        var result: [[UInt16]] = []
        var chunk: [UInt16] = []
        for scalar in text.unicodeScalars {
            let units = Array(String(scalar).utf16)
            if chunk.count + units.count > 20 {
                result.append(chunk)
                chunk = []
            }
            chunk.append(contentsOf: units)
        }
        if !chunk.isEmpty { result.append(chunk) }
        return result
    }

    private static func key(_ code: CGKeyCode, flags: CGEventFlags = []) throws {
        guard let down = CGEvent(keyboardEventSource: nil, virtualKey: code, keyDown: true),
            let up = CGEvent(keyboardEventSource: nil, virtualKey: code, keyDown: false)
        else {
            throw LibraryValidationError("macOS could not create a keyboard event.")
        }
        for event in [down, up] {
            event.flags = flags
            event.setIntegerValueField(.eventSourceUserData, value: marker)
            event.post(tap: .cghidEventTap)
        }
    }
}
